services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rag-server:
    build: .
    container_name: rag-server
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
